# Generated by Django 5.0.6 on 2024-09-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
